Add: 06.wc（wc コマンドを作る）
nouvelle/ruby-practices pull request #9
Opened 2022-08-15 16:21 UTC by nouvelle

2022-08-21 03:45 UTC, u1tnk requested changes
`echo "test" | ruby wc.rb -l`
をするとおかしくなります。

標準入力のときとファイルを読み取るときの処理の共通化ができていません。
ヒントとして標準入力はファイル名が無いファイルと思えば共通化できると思います 💪

2022-08-21 03:45 UTC, u1tnk commented on 06.wc/wc.rb
> +def calc_filenames(filenames, is_l, is_w, is_c, is_all)
メソッド名としてはそれぞれのファイルごとの計算のみをするように見えますが、実際は計算に加え出力もしてますし、total行の処理までしていて、
- 名前と中身があっていない
- このメソッドの責務が多過ぎる

という点の改善が必要です。
- 出力を分けるか、メソッド名を変える
- totalは別のメソッドにする

を対応すると良いと思います。

2022-08-21 03:45 UTC, u1tnk commented on 06.wc/wc.rb
> +    strings = File.read(filename)
stringsだと文字列の配列のように見えますが(慣習として複数形だと配列と判断するので)、実際には文字列だと思います。
だとすると stringになりますが、handle_stdinメソッドでは strという変数名を使っていて統一感がありません。
また、handle_stdinメソッドであればどんな文字列が来るか分からないので `str` イコール`汎用的な文字列`という変数で問題ありませんが、この部分はファイルから読み取った文字列なので、stringでもダメというほどでは無いですが、「ファイルの中身の文字列」という事が分かる変数名だとなお良いですね。

2022-08-21 15:08 UTC, nouvelle commented on 06.wc/wc.rb
> +    strings = File.read(filename)
`str_of_file` とかいかがでしょう？？いい名前が思いつかず...(-"-;

2022-08-22 02:31 UTC, u1tnk commented on 06.wc/wc.rb
> +    strings = File.read(filename)
特に textとstringだとあまり変わらないのでstringのままで良いです。(データベースの型定義とかを参考にするとtextの方がstringよりも長い文字列を指すようなので、その意味でもstringの方が良いですね)
なのでこの路線だと`string_of_file`の方が良いですが、よく見るものだと `content`/`file_content`とかですね。http headerにも content-length というものがあり、中身のデータという意味になるので。

2022-08-22 02:37 UTC, u1tnk requested changes

2022-08-22 02:37 UTC, u1tnk commented on 06.wc/wc.rb
> +def calc_filename(filename, is_l, is_w, is_c, is_all)
calc_filenameとhandle_stdinがほぼ同じ処理が重複しています。
文字列を取得する処理(fileを読み込む、stdinから取得する)を分ければこのメソッドが共通化できるはずです 💪

2022-08-22 02:37 UTC, u1tnk commented on 06.wc/wc.rb
> +  l = format('% 8d', line_count(text_of_file)) if is_l || is_all
前述した理由でこの省略もあまり良くないです。これだと文字列フォーマットもしているので line_partとかでしょうか 🤔

2022-08-22 13:31 UTC, u1tnk requested changes
共通化のところは良いと思います 👍 

指摘が漏れていたところと変数名のちょっとしたところ指摘しております 🙏

2022-08-22 13:31 UTC, u1tnk commented on 06.wc/wc.rb
> +    lines_part, words_part, counts_part = calc_string(string_of_file, is_l, is_w, is_c, is_all)
同じく countsが気になります。

2022-08-23 16:02 UTC, u1tnk approved these changes

2022-08-24 08:33 UTC, merged